# This is the configuration file for Cursewords.
#
# This file is expected to be named "cursewords.toml". It can be kept in the
# current working directory where Cursewords is run or in $HOME/.config/.
#
# Most options can be overridden on the command line, like so:
#    cursewords --twitch.nickname=mybot --twitch.enable-clue=false puzfile.puz

# Log messages to a file named cursewords.log.
log_to_file = false

[twitch]
# Set this to "true" to enable Twitch support.
enable = false

# Viewers can guess words in the puzzle and cause things to happen.
enable_guessing = true

# Viewers can type "!clue 22d" to have the bot post a clue to the chat room.
enable_clue = true

# The Twitch account that Cursewords should use to connect.
nickname = "..."

# The Twitch channel that Cursewords should join.
channel = "..."

# The OAuth token is a temporary password that Cursewords will use to connect
# to Twitch. This is *not* the Twitch password for the account.
#
# To get the OAuth token, sign in to this website with the bot's Twitch
# account and password:
#   https://twitchapps.com/tmi/
#
# The OAuth token is a string that begins "oauth:" followed by letters and
# numbers. Keep the OAuth token secret.
#
# To revoke access for this token, sign in to Twitch.tv with the bot account,
# go to Settings, then select the Connections tab. Locate the "Twitch
# Developer" connection then click Disconnect.
oauth_token = "oauth:..."

# If enable_clue is true, the number of seconds a given user must wait between
# clue requests.
clue_cooldown_per_person = 10
